config/routes.rb
Rails.application.routes.draw do
	devise_for :user, controllers: {:omniauth_callbacks => "omniauth_callbacks"}
	root "homes#index"
	resources :reports
	resources :patients do
		collection do
			post "report_generator"
			post "export_options"
		end
		member do
			get "report"
		end
	end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
	belongs_to :report
	mount_uploader :name, AvatarUploader
end

app/models/company.rb
class Company < ApplicationRecord
	belongs_to :user
	has_many :patients
end

app/models/patient.rb
class Patient < ApplicationRecord
	validates_presence_of :first_name
	validates_presence_of :last_name
	validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP } 
	belongs_to :company, optional: true
	has_many :reports
	has_many :users, through: :reports

end

app/models/report.rb
class Report < ApplicationRecord
	belongs_to :user
	belongs_to :patient
	has_many :attachments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]
  has_one :company
  has_many :reports
	has_many :patients, through: :reports
  after_create :add_company

  def add_company
  	self.create_company(name: "Company #{self.id}") if !self.company
  end

  def patients
    attributes = %w{id last_name first_name email}
    patients = self.company.patients
    CSV.generate(headers: true) do |csv|
      csv << attributes
      patients.each do |user|
        csv << attributes.map{ |attr| user.send(attr) }
      end
    end
  end

  def self.from_omniauth(auth)
    where(email: auth.info.email).first_or_initialize do |u|
        u.email = auth.info.email
        u.password = Devise.friendly_token[0, 20]                
        u.save
    end    
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
	before_action :set_current_user
	before_action :set_patients

	def after_sign_in_path_for(resource)
		patients_path
	end

	def set_current_user
		@user = current_user
	end

	def set_patients
		@patients = @user.company.patients if current_user
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def index
	end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def google_oauth2
    @user =  User.from_omniauth(request.env["omniauth.auth"])
    if @user.present?
      sign_in(@user, :bypass => true)      
      redirect_to new_user_session_path      
    else
      flash[:error] = "Please register first."
      redirect_to new_user_session_path
    end
  end
  
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
	require 'csv'
	require 'json'
	require 'nokogiri'
	before_action :find_patient, only: [:edit, :destroy, :update, :report ,:report_generator]


  def index
  end

  def new
  	@patient = Patient.new
  end

  def create
  	extension = file_extension(params[:file])
  	if extension.include?('csv')
  		import_csv
  	elsif extension.include?('json')
  		import_json
  	elsif extension.include?('xml')
  		import_xml
  	elsif ['csv','json','xml'].exclude?(extension)
  		flash[:error] = "Only accept CSV/JSON/XML format"
  		redirect_to new_patient_path
  	end
  	if @errors.present?
  		flash[:error] = "Not saved, please see the error below"
			render :new
  	end
  end

  def edit
  end

  def update
  	if @patient.update_attributes(patient_params)
  		flash[:notice] = "Patient has been updated"
  		redirect_to patients_path
  	end
  end

  def destroy
  	if @patient.destroy
  		flash[:notice] = "Patient has been deleted"
  		redirect_to patients_path
  	end
  end

  def report
  end

  def report_generator
  	if @patient.present? && params.present?
  		params["reports"].keys.each do |param|
  			report = Report.new(age: params[:reports][param]["age"],parents_name:params[:reports][param]["parents_name"],describe_problem: params[:reports][param]["describe_problem"],amount: params[:reports][param]["amount"],user_id: @user.id, patient_id: @patient.id)
  			report.update(user_id: @user.id, patient_id: @patient.id)
  			report.attachments.create(name: params[:attachments][param])
  		end
  	end
  	flash[:notice] = "Reports generated successfully"
  	redirect_to patients_path
  end

  def import_csv
  	csv = CSV.read(params[:file], :headers=>true)
  	@errors = []
		csv.each do |row|
  		patient = Patient.new(row.to_h)
  		if patient.save
  			patient.update(company_id: @user.company.try(:id))
  		else 
  			@errors << row["first_name"]
  		end
		end
		redirection
  end

  def import_json
  	@errors = []
  	patient_list = JSON.parse(File.read(params[:file]))
  	patient_list["patients"].each do |patient_hash|
  		patient = Patient.new(patient_hash)
  		if patient.save
  			patient.update(company_id: @user.company.try(:id))
  		else
  			@errors << patient_hash[:first_name]
  		end
		end
		redirection
  end

  def import_xml
  	@errors = []
		doc = Nokogiri::XML(params[:file])
		doc.css(:patient).each do |patient|
			column = patient.children
			patient = Patient.new(first_name: column.css("first_name").inner_text,last_name: column.css("last_name").inner_text,email: column.css("email").inner_text)
			if patient.save
				patient.update(company_id: @user.company.try(:id))
			else
				@errors << column.css("first_name").inner_text
			end
		end
		redirection
  end

  def export_options
  	if params[:type].eql?('csv')
  		export_csv
  	elsif params[:type].eql?('json')
  		export_json
  	end
  end

  def export_csv
  	file = "#{Rails.root}/public/patient_data.csv"
		headers = ["Patient ID", "Name", "Price", "Description"]
		respond_to do |format|
      format.csv { send_data @user.patients, filename: "patients-#{Date.today}.csv" }
    end
  end

  def export_json
  	data = @patients.to_json
    send_data data, :type => 'application/json; header=present', :disposition => "attachment; filename=patients.json"
  end

  private

  def find_patient
  	@patient = Patient.find_by(id: params[:id])
  end

  def redirection
  	unless @errors.present?
			flash[:notice] = "Patients imported successfully"
			redirect_to new_patient_path
		end
  end

  def file_extension(file)
		File.extname(file.original_filename)
	end

	def patient_params
		params.require(:patient).permit(:first_name, :last_name)
	end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
	before_action :set_patient, only: [:show]
	before_action :set_report, only: [:edit,:update,:destroy]
  
  def index
  end

  def new
  end

  def edit
  end

  def show
  end

  def update
  	if @report.update_attributes(report_params)
  		flash[:notice] = "Report has been updated"
  		redirect_to report_path(@report.patient_id)
  	end
  end

  def destroy
  	if @report.destroy
  		flash[:notice] = "Report has been deleted"
  		redirect_to report_path(@report.patient_id)
  	end
  end

  private
  def set_patient
  	@patient = Patient.find_by(id: params[:id])
  end
  def set_report
  	@report = Report.find_by(id: params[:id])
  end

  def report_params
  	params.require(:report).permit(:age,:parents_name,:describe_problem,:amount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/homes/index.html.erb
<%= link_to 'Sign in', new_user_session_path %>
<%= link_to 'Sign Up', new_user_registration_path %>
(OR)
<a href="<%= user_omniauth_authorize_path(:google_oauth2) %>" class="flex flex-justify-between" style="">
  <img src="/assets/google.png" alt="">&nbsp;
  <div class="signup-social">Signup with Google</div>
</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hospital</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag 'application' %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.css">

    <script type="text/javascript" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.js"></script>

  </head>

  <body>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% else %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <% if user_signed_in? %>    
    <%= link_to 'Logout', destroy_user_session_path, method: 'delete', class: 'btn btn-danger' %>
  <% end %>
  <div class="container">
    <%= yield %>
  </div>


  </body>
</html>

app/views/patients/_form.html.erb
<style type="text/css">
	.pat-err p{
		color: red;
	}
	.pat-save{
		color: green;
	}
</style>

<h1>Import Patients</h1>
<div class="pat-err">
	<% if @errors.present? %>
		Below rows are not saved due to error<br>
		<% @errors.each do |err| %>
			<p><%= "#{err} row" %><br></p>
		<% end %>
	<% end %>
</div>

<div class="container">
	<%= form_tag '/patients', multipart: true do %>
		<div class="row">
		<label>Upload the CSV/JSON/XML format</label>
		<%= file_field_tag 'file', accept: '.csv,.json,.xml', class: 'form-control upload-file', required: true %><br>
		<%= submit_tag 'Create', class: 'btn btn-success' %>
		</div>
	<% end %>
</div>

<%= link_to "Back", patients_path %>

app/views/patients/edit.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Email</th>
      <th scope="col">Action</th>
    </tr>
  </thead>

  <tbody>
  <%= form_for(@patient, method: :put) do |f| %>
    <tr>
      <td><%= f.text_field :first_name, value: @patient.first_name %></td>
      <td><%= f.text_field :last_name, value: @patient.last_name %></td>
      <td><%= f.text_field :email, value: @patient.email, readonly: true %></td>
      <td><%= f.submit "Update", class: 'btn btn-success' %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Back', patients_path, class: 'btn' %>

app/views/patients/index.html.erb
<h1>Patients</h1>

<table class="display" id="patient_table">
  <thead>
    <tr>
      <th>Nos</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
  <% if @patients.present? %>
	  <% @patients.each_with_index do |patient,index| %>
		    <tr>
		      <td scope="row"><%= index+1 %></td>
		      <td><%= patient.first_name %></td>
		      <td><%= patient.last_name %></td>
		      <td><%= patient.email %></td>
		      <td><%= link_to "Add Reports", report_patient_path(patient.id) %> | <%= link_to "Edit Reports", report_path(patient.id) %> | <%= link_to 'Edit', edit_patient_path(patient) %> | <%= link_to 'Delete', "/patients/#{patient.id}", method: :delete ,data: {confirm: "Are you sure?"} %></td>		    
		    </tr>
		 <% end %>
	<% else %>
		<tr><th colspan="5">No patients</th></tr>
	<% end %>
  </tbody>
</table>

<div class="row">
	<div class="col-sm-4">
		<%= link_to 'Export as CSV', export_options_patients_path(type: 'csv', format: 'csv'), method: :post, class: 'btn btn-success' %>
	</div>
	<div class="col-sm-4">
		<%= link_to 'Export as JSON', export_options_patients_path(type: 'json'), method: :post, class: 'btn btn-success' %>
	</div>
</div><br>


<div class="log">
	<%= link_to 'Add Patients', new_patient_path, class: 'btn btn-primary' %>
</div>

app/views/patients/new.html.erb
<%= render 'form' %>

app/views/patients/report.html.erb
<div class="container">
	<div class="info">
		<p>Patient Email: <%= @patient.email %></p>
	</div>

	<div class="adNew">
		<a class="add_now btn btn-primary" data-count="0">Add more Report</a>
	</div><br>

	<%= form_tag(report_generator_patients_path, multipart: true) do %>
	<%= hidden_field_tag "id", @patient.id %>
		<div id="appendDiv">
			<div class="addMore">
				<div class="row">
					
					<div class="col-sm-4">
						<input type="text" class="form-control age" name="reports[0]age" placeholder="Age" max="3" required="true">
					</div>

					<div class="col-sm-4">
						<input type="text" class="form-control parent_name" name="reports[0]parents_name" placeholder="Parents Name" required="true">
					</div>

					<div class="col-sm-4">
						<input type="text" class="form-control problem" name="reports[0]describe_problem" placeholder="Describe Problem" required="true">
					</div>
				</div><br>
				<div class="row">
					<div class="col-sm-6">
						<input type="text" class="form-control amount" name="reports[0]amount" placeholder="Amount" required="true">
					</div>
					<div class="col-sm-6">
						<input type="file" class="form-control attachment" name="attachments[0]attachment" required="true">
					</div>
				</div>

			</div><br>
		</div>

		<div class="actions">
			<%= submit_tag "Generate", class: 'btn btn-primary' %>
		</div>
	<% end %>

</div>

<script type="text/javascript">
	$(document).ready(function(){
		$('.add_now').click(function(){
			var report_attr_count = $(this).attr('data-count');
			var report = parseInt(report_attr_count) + 1;
			var html = $('.addMore').html();
			$('#appendDiv').append(html);
			var ele1 = $('.age').last();
			var ele2 = $('.parent_name').last();
			var ele3 = $('.problem').last();
			var ele4 = $('.amount').last();
			var ele5 = $('.attachment').last();
			$(ele1).attr('name', ('reports['+report+']age')).attr('required',true);
			$(ele2).attr('name', ('reports['+report+']parents_name')).attr('required',true);
			$(ele3).attr('name', ('reports['+report+']describe_problem')).attr('required',true);
			$(ele4).attr('name', ('reports['+report+']amount')),attr('required',true);
			$(ele5).attr('name', ('attachments['+report+']attachment')).attr('required',true);
			$('.add_now').attr('data-count', report);
		})
	})
</script>

app/views/reports/_form.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">Age</th>
      <th scope="col">Parent Name</th>
      <th scope="col">Describe Problem</th>
      <th scope="col">Amount</th>
      <th scope="col">Action</th>
    </tr>
  </thead>

  <tbody>
  <%= form_for(@report, method: :put) do |f| %>
    <tr>
      <td><%= f.text_field :age, value: @report.age %></td>
      <td><%= f.text_field :parents_name, value: @report.parents_name %></td>
      <td><%= f.text_field :describe_problem, value: @report.describe_problems %></td>
      <td><%= f.text_field :amount, value: @report.amount %></td>
      <td><%= f.submit "Update", class: 'btn btn-success' %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Back', patients_path, class: 'btn' %>

app/views/reports/edit.html.erb
<h1>Edit Reports</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Age</th>
      <th scope="col">Parents Name</th>
      <th scope="col">Describe Problem</th>
      <th scope="col">Amount</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>

  <tbody>
  <%= form_for(@report, method: :put) do |f| %>
    <tr>
      <td><%= f.text_field :age, value: @report.age %></td>
      <td><%= f.text_field :parents_name, value: @report.parents_name %></td>
      <td><%= f.text_field :describe_name, value: @report.describe_problem %></td>
      <td><%= f.text_field :amount, value: @report.amount %></td>
			<td><%= f.submit 'Update', class: 'bt btn-primary' %></td>
      <td><%= link_to 'Delete', "/patients/#{@report.id}", method: :delete ,data: {confirm: "Are you sure?"} %></td>
    </tr>
   <% end %>
  </tbody>
</table>

app/views/reports/new.html.erb
<h1>Reports#new</h1>
<p>Find me in app/views/reports/new.html.erb</p>

app/views/reports/show.html.erb
<h1>Patient Reports</h1>

<table class="display" id="report_table">
  <thead>
    <tr>
      <th>Age</th>
      <th>Parent Name</th>
      <th>Describe Problem</th>
      <th>Amount</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
	  <% reports = @patient.reports %>
	  <% reports.each do |report| %>
	    <tr>
	      <td><%= report.age %></td>
	      <td><%= report.parents_name %></td>
	      <td><%= report.describe_problem %></td>
	      <td><%= report.amount %></td>
	      <td><%= link_to "Edit Report", edit_report_path(report.id) %> | <%= link_to 'Delete', "/reports/#{report.id}", method: :delete ,data: {confirm: "Are you sure?"} %></td>
	    </tr>
	  <% end %>
  </tbody>
</table>


<div class="log">
	<%= link_to 'Back', patients_path %>	
</div>